import type { Resource } from "./types";

/**
 * Rated for THIS plan: a strong-prépa freshman, 2 years, heading for M2 MVA.
 * rating 5 = spine of the plan, 4 = strong, 3 = useful reference / situational.
 */
export const resources: Resource[] = [
  // ─────────────────────────── MATH ───────────────────────────
  {
    id: "boyd",
    title: "Convex Optimization",
    by: "Boyd & Vandenberghe (CUP, free PDF)",
    type: "book",
    url: "https://web.stanford.edu/~boyd/cvxbook/",
    tracks: ["math", "ml"],
    rating: 5,
    effort: "~730 pp — plan ch.1-5 + 9-11 seriously (~120 h)",
    verdict:
      "The book you asked for, and the right call. Ch. 2-5 (sets, functions, problems, duality) are the actual master-level content; ch. 9-11 (unconstrained, equality, interior-point) are what make you dangerous in ML. Skip ch. 6-8 on first pass, mine them for examples later. Prose is unusually clean — read it linearly, do 5-8 exercises per chapter, not more.",
    when: "Phase 1-3 (W1-W25), revisited in Phase 6 for the MVA course.",
  },
  {
    id: "ee364a",
    title: "EE364a — Convex Optimization I (2023 lectures)",
    by: "Stephen Boyd, Stanford",
    type: "course",
    url: "https://www.youtube.com/playlist?list=PLoROMvodv4rMJqxxviPa4AmDClvcbHi6h",
    tracks: ["math"],
    rating: 5,
    effort: "19 × 80 min + slides + homework",
    verdict:
      "Boyd teaching his own book, with the 2023 recording quality. Use lectures as a first pass over each chapter (he tells you what matters), then read. Homework sets on the course site are the real value — they force CVXPY modelling, which is the 'abstract → real' bridge you said you're missing.",
    when: "Paired 1:1 with the book, W3-W25.",
  },
  {
    id: "ee364a-site",
    title: "EE364a course site (slides, homework, solutions)",
    by: "Stanford",
    type: "course",
    url: "https://web.stanford.edu/class/ee364a/",
    tracks: ["math"],
    rating: 5,
    effort: "Homework: ~4 h/set",
    verdict:
      "Slides are a compressed version of the book — ideal for revision. Additional exercises repo (cvxbook_additional_exercises) is where the applied problems live.",
    when: "Every math week.",
  },
  {
    id: "ee364b",
    title: "EE364b — Convex Optimization II",
    by: "Boyd, Stanford",
    type: "course",
    url: "https://web.stanford.edu/class/ee364b/",
    tracks: ["math", "ml"],
    rating: 4,
    effort: "~40 h",
    verdict:
      "Subgradients, proximal methods, ADMM, stochastic programming, decomposition. This is the layer that connects convexity to what optimizers actually do in deep learning. Only after 364a is fully digested.",
    when: "Phase 6-7 (W52-W85).",
  },
  {
    id: "rouviere",
    title: "Petit guide de calcul différentiel",
    by: "François Rouvière (Cassini)",
    type: "book",
    url: "https://www.eyrolles.com/Entreprise/Livre/petit-guide-de-calcul-differentiel-9782842251864/",
    tracks: ["math"],
    rating: 5,
    effort: "133 corrected exercises — do ~50 (~40 h)",
    verdict:
      "The fastest repair for exactly your weak spot. French, agrég-level, but the first 5 chapters are pure differential calculus with geometry and 190 figures. Differentials as linear maps, inverse/implicit function theorems, submanifolds, Lagrange multipliers done properly. Nothing in English is this efficient for a prépa brain.",
    when: "Phase 1 (W1-W7) — do this BEFORE Boyd ch.3, it removes 80% of your friction.",
  },
  {
    id: "18065",
    title: "18.065 Matrix Methods in Data Analysis, Signal Processing & ML",
    by: "Gilbert Strang, MIT OCW",
    type: "course",
    url: "https://ocw.mit.edu/courses/18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018/",
    tracks: ["math", "ml"],
    rating: 4,
    effort: "36 lectures, watch at 1.5× (~25 h)",
    verdict:
      "Not a proof course — a 'what linear algebra actually does in ML' course. SVD, low-rank, pseudo-inverse, norms, gradient descent geometry. You already have the algebra (13/20 X); this gives it computational meaning. Skip 18.06, you don't need it.",
    when: "Phase 1-2, in parallel with Boyd ch.2-3.",
  },
  {
    id: "trefethen",
    title: "Numerical Linear Algebra",
    by: "Trefethen & Bau (SIAM)",
    type: "book",
    url: "https://people.maths.ox.ac.uk/trefethen/text.html",
    tracks: ["math", "cs"],
    rating: 4,
    effort: "40 short lectures — do 1-20 (~30 h)",
    verdict:
      "The single most elegant numerics book. Conditioning, stability, QR, least squares, iterative methods. Directly explains why your solvers explode in robotics (Jacobian pseudo-inverse, IK conditioning) and why float32 training does what it does.",
    when: "Phase 3-4.",
  },
  {
    id: "nocedal",
    title: "Numerical Optimization",
    by: "Nocedal & Wright (Springer)",
    type: "book",
    url: "https://link.springer.com/book/10.1007/978-0-387-40065-5",
    tracks: ["math", "rob"],
    rating: 4,
    effort: "Reference — read ch. 2-6, 10, 18 (~35 h)",
    verdict:
      "The non-convex counterpart to Boyd, and the reference behind every trajectory optimizer (SQP, interior point, line search vs trust region, Gauss-Newton/Levenberg-Marquardt). You need ch.10 (least squares) and ch.18 (SQP) for MPC and bundle adjustment.",
    when: "Phase 5-7, on demand from robotics.",
  },
  {
    id: "18650",
    title: "18.650 Statistics for Applications",
    by: "Philippe Rigollet, MIT OCW",
    type: "course",
    url: "https://ocw.mit.edu/courses/18-650-statistics-for-applications-fall-2016/",
    tracks: ["math", "ml"],
    rating: 5,
    effort: "24 lectures (~35 h)",
    verdict:
      "Rigollet is a former MVA-sphere probabilist and this is the cleanest bridge from prépa probability to statistical learning: MLE, Fisher information, delta method, hypothesis testing, regression, PCA — all with the asymptotics stated properly. MVA assumes exactly this.",
    when: "Phase 4-5 (W26-W42). Prerequisite for Bach and for MVA theory courses.",
  },
  {
    id: "vershynin",
    title: "High-Dimensional Probability",
    by: "Roman Vershynin (free PDF)",
    type: "book",
    url: "https://www.math.uci.edu/~rvershyn/papers/HDP-book/HDP-book.html",
    tracks: ["math", "ml"],
    rating: 4,
    effort: "Ch. 1-6 (~40 h)",
    verdict:
      "Concentration inequalities, sub-gaussian tails, random matrices, Johnson-Lindenstrauss. This is the toolkit that separates 'I use ML' from 'I can read a NeurIPS proof'. Hard but self-contained and beautifully written.",
    when: "Phase 7 (W69-W85) — direct MVA prep.",
  },
  {
    id: "bach",
    title: "Learning Theory from First Principles",
    by: "Francis Bach (MIT Press, free draft)",
    type: "book",
    url: "https://www.di.ens.fr/~fbach/ltfp_book.pdf",
    tracks: ["math", "ml"],
    rating: 5,
    effort: "Ch. 1-9 (~60 h)",
    verdict:
      "Written by an MVA professor, and effectively the syllabus of the theory half of MVA. Statistical learning, empirical risk, kernels, sparsity, neural nets — with the analysis done, not waved at. If you can work through this by summer 2028, you are MVA-ready on the maths side.",
    when: "Phase 7-8. Read after 18.650 + Boyd.",
  },
  {
    id: "cot",
    title: "Computational Optimal Transport",
    by: "Peyré & Cuturi (free)",
    type: "book",
    url: "https://optimaltransport.github.io/book/",
    tracks: ["math", "ml"],
    rating: 3,
    effort: "Ch. 1-4 + Sinkhorn notebooks (~15 h)",
    verdict:
      "Peyré teaches the MVA OT course and it is one of the flagship modules. Not needed early — but a 15 h skim in year 2 makes you look like you know the house style, and Sinkhorn shows up in vision (point-cloud matching, flow matching).",
    when: "Phase 8, optional-but-strategic.",
  },
  {
    id: "numerical-tours",
    title: "Numerical Tours",
    by: "Gabriel Peyré",
    type: "practice",
    url: "https://www.numerical-tours.com/",
    tracks: ["math", "cs"],
    rating: 4,
    effort: "1-3 h per tour",
    verdict:
      "Executable notebooks for wavelets, TV denoising, proximal splitting, OT. The single best 'abstract → code' exercise set in French applied maths, and again: house style of MVA.",
    when: "Any week where the maths feels too abstract. Use as the closing 30 min.",
  },
  {
    id: "aspremon",
    title: "MVA — Convex Optimization, Algorithms and Applications",
    by: "Alexandre d'Aspremont, ENS",
    type: "course",
    url: "https://www.di.ens.fr/~aspremon/OptConvexeM2.html",
    tracks: ["math"],
    rating: 4,
    effort: "Slides + past exams",
    verdict:
      "The actual MVA optimization course page, publicly posted with videos and past exams. Use it as your benchmark: when you can do these exams cold, your optimization is at MVA entry level.",
    when: "Checkpoint at end of Phase 6 and Phase 8.",
  },

  // ─────────────────────────── CS ───────────────────────────
  {
    id: "missing-semester",
    title: "The Missing Semester of Your CS Education",
    by: "MIT",
    type: "course",
    url: "https://missing.csail.mit.edu/",
    tracks: ["cs", "rob"],
    rating: 5,
    effort: "11 × 1 h lectures + exercises (~15 h)",
    verdict:
      "Shell, git, debugging, profiling, tooling. Cheapest possible ROI: it removes the friction that stops prépa students from ever finishing a project. Do it in week 1-2, once, properly.",
    when: "W1-W2. Non-negotiable first step.",
  },
  {
    id: "mit6006",
    title: "6.006 Introduction to Algorithms (Spring 2020)",
    by: "Demaine, Ku, Solomon — MIT OCW",
    type: "course",
    url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/",
    tracks: ["cs"],
    rating: 5,
    effort: "26 lectures + problem sessions + psets (~70 h)",
    verdict:
      "The 2020 rewrite is far better than the 2011 one: it teaches a reduction-based way of thinking, not a list of algorithms. You already know Dijkstra and sorting — the value here is rigour about invariants, amortization and correctness proofs, plus the problem sessions, which are modelled interview answers.",
    when: "Phase 1-2 (W1-W16). Prerequisite for everything CS after.",
  },
  {
    id: "mit6046",
    title: "6.046J Design and Analysis of Algorithms",
    by: "MIT OCW",
    type: "course",
    url: "https://ocw.mit.edu/courses/6-046j-design-and-analysis-of-algorithms-spring-2015/",
    tracks: ["cs"],
    rating: 4,
    effort: "24 lectures (~50 h)",
    verdict:
      "Divide & conquer, randomization, amortized analysis, network flow, NP-completeness, approximation. This is the master-level algorithms layer and where hard interview questions actually come from.",
    when: "Phase 3-4 (W17-W33).",
  },
  {
    id: "clrs",
    title: "Introduction to Algorithms (CLRS, 4th ed.)",
    by: "Cormen, Leiserson, Rivest, Stein",
    type: "book",
    url: "https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/",
    tracks: ["cs"],
    rating: 3,
    effort: "Reference only",
    verdict:
      "Do not read it cover to cover — you'd burn 300 h. Use it as the lookup layer behind 6.006/6.046: read the chapter matching the lecture, do 3 exercises, move on.",
    when: "Alongside 6.006/6.046 only.",
  },
  {
    id: "cp-algorithms",
    title: "cp-algorithms",
    by: "e-maxx (translated)",
    type: "practice",
    url: "https://cp-algorithms.com/",
    tracks: ["cs"],
    rating: 4,
    effort: "Snack-sized",
    verdict:
      "Terse, correct implementations of every classical algorithm with proofs of complexity. Best place to check your implementation against a reference after you've written it yourself.",
    when: "Throughout Phase 2-5.",
  },
  {
    id: "cses",
    title: "CSES Problem Set",
    by: "Antti Laaksonen",
    type: "practice",
    url: "https://cses.fi/problemset/",
    tracks: ["cs"],
    rating: 5,
    effort: "300 problems — target 150 (~120 h over 2 years)",
    verdict:
      "The best-ordered problem set in existence: sorting/searching → DP → graphs → range queries → trees. Unlike LeetCode it has no noise and no chatty editorials, so it builds actual implementation speed in C++. This is your daily driver for the first year.",
    when: "W3 onward, 3-5 problems/week, forever.",
  },
  {
    id: "cph",
    title: "Competitive Programmer's Handbook",
    by: "Antti Laaksonen (free PDF)",
    type: "book",
    url: "https://cses.fi/book/book.pdf",
    tracks: ["cs"],
    rating: 4,
    effort: "300 pp, read as you solve",
    verdict:
      "Companion to CSES. Fastest path from 'knows what a graph is' to 'implements Dijkstra with a priority queue in 4 minutes without bugs' — which is literally the interview bar.",
    when: "Phase 1-3.",
  },
  {
    id: "neetcode",
    title: "NeetCode 150 / roadmap",
    by: "NeetCode",
    type: "practice",
    url: "https://neetcode.io/roadmap",
    tracks: ["cs"],
    rating: 4,
    effort: "150 problems (~80 h)",
    verdict:
      "The interview-shaped complement to CSES: pattern-grouped, with clean video explanations. Do it in year 2 when the algorithms are already there — otherwise you memorise patterns without understanding.",
    when: "Phase 6-8 (W52+), 4 problems/week.",
  },
  {
    id: "learncpp",
    title: "LearnCpp.com",
    by: "Alex",
    type: "course",
    url: "https://www.learncpp.com/",
    tracks: ["cs", "rob"],
    rating: 4,
    effort: "Chapters 1-22 (~40 h)",
    verdict:
      "Best free modern C++ tutorial, and it is actually modern (C++17/20, RAII, smart pointers, move semantics). Your OCaml background makes the type discipline easy; what you're missing is memory model and tooling.",
    when: "Phase 1-2, 3 h/week alongside 6.006.",
  },
  {
    id: "cs106l",
    title: "CS106L — Standard C++ Programming",
    by: "Stanford",
    type: "course",
    url: "https://web.stanford.edu/class/cs106l/",
    tracks: ["cs"],
    rating: 4,
    effort: "~20 h",
    verdict:
      "Short, opinionated, teaches idiomatic STL and templates rather than 'C with classes'. Perfect second C++ pass; the assignments are small and finishable.",
    when: "Phase 3.",
  },
  {
    id: "effective-cpp",
    title: "Effective Modern C++",
    by: "Scott Meyers",
    type: "book",
    url: "https://www.oreilly.com/library/view/effective-modern-c/9781491908419/",
    tracks: ["cs"],
    rating: 3,
    effort: "42 items, ~20 h",
    verdict:
      "Read once you've written ~3 kLOC of C++ and are hitting rvalue/lifetime confusion. Before that it's noise.",
    when: "Phase 5+.",
  },
  {
    id: "csapp",
    title: "CS:APP / CMU 15-213 Introduction to Computer Systems",
    by: "Bryant & O'Hallaron",
    type: "course",
    url: "https://csapp.cs.cmu.edu/",
    tracks: ["cs"],
    rating: 5,
    effort: "Book ch. 1-6, 8-9 + bomb/attack/malloc labs (~80 h)",
    verdict:
      "The course that turns a 'coder' into someone who understands machines: memory hierarchy, cache behaviour, linking, exceptions, concurrency. The labs (bomb, attack, cachelab, malloc) are the best assignments in undergraduate CS, full stop. Also the source of the hardest non-algorithmic interview questions and the reason your CUDA/embedded code will be fast.",
    when: "Phase 4-6 (W26-W68). Prerequisite for serious CUDA and embedded work.",
  },
  {
    id: "ostep",
    title: "Operating Systems: Three Easy Pieces",
    by: "Arpaci-Dusseau (free)",
    type: "book",
    url: "https://pages.cs.wisc.edu/~remzi/OSTEP/",
    tracks: ["cs"],
    rating: 4,
    effort: "Virtualization + concurrency sections (~35 h)",
    verdict:
      "Readable, honest, free. You need processes/threads/locks/scheduling for real-time robotics (why your control loop jitters) and for interviews. Skip persistence on first pass.",
    when: "Phase 5-6.",
  },
  {
    id: "fluent-python",
    title: "Fluent Python (2nd ed.)",
    by: "Luciano Ramalho",
    type: "book",
    url: "https://www.oreilly.com/library/view/fluent-python-2nd/9781492056348/",
    tracks: ["cs", "ml"],
    rating: 3,
    effort: "Selected chapters (~15 h)",
    verdict:
      "You'll write a lot of Python for ML; this makes it good Python (data model, iterators, decorators, typing, concurrency). Cherry-pick, don't read linearly.",
    when: "Phase 2-3.",
  },
  {
    id: "sysdesign",
    title: "System Design Primer",
    by: "donnemartin (GitHub)",
    type: "repo",
    url: "https://github.com/donnemartin/system-design-primer",
    tracks: ["cs"],
    rating: 3,
    effort: "~25 h",
    verdict:
      "Only relevant for software-engineering interviews (internships in year 2). For research/robotics roles, replace with 'design an ML system' practice. Keep it light.",
    when: "Phase 7-8, before internship applications.",
  },
  {
    id: "ddia",
    title: "Designing Data-Intensive Applications",
    by: "Martin Kleppmann",
    type: "book",
    url: "https://dataintensive.net/",
    tracks: ["cs"],
    rating: 3,
    effort: "~30 h",
    verdict:
      "Excellent book, wrong priority for you right now. Read ch. 1-4 in year 2 only if you're targeting big-tech SWE internships alongside research.",
    when: "Optional, Phase 8.",
  },

  // ─────────────────────────── COMPUTER VISION ───────────────────────────
  {
    id: "fpcv",
    title: "First Principles of Computer Vision",
    by: "Shree Nayar, Columbia",
    type: "course",
    url: "https://fpcv.cs.columbia.edu/",
    tracks: ["cs", "rob"],
    rating: 5,
    effort: "~60 short videos (~25 h)",
    verdict:
      "The best explanation of classical vision that exists on video: image formation, radiometry, features, stereo, optical flow — each in a tight 10-20 min module with real optics. Watch this BEFORE any deep-learning vision course; it's the part that makes you good at the racing car and the drone, where a CNN is often the wrong tool.",
    when: "Phase 2-3 (W8-W25).",
  },
  {
    id: "szeliski",
    title: "Computer Vision: Algorithms and Applications (2nd ed.)",
    by: "Richard Szeliski (free PDF)",
    type: "book",
    url: "https://szeliski.org/Book/",
    tracks: ["cs", "ml"],
    rating: 4,
    effort: "Reference, ~1200 pp",
    verdict:
      "The encyclopedia. Never read linearly — use it to go deeper on whatever Nayar or CS231n just showed you, and for its enormous, well-curated bibliography when you start reading papers.",
    when: "Throughout.",
  },
  {
    id: "cs231n",
    title: "CS231n — Deep Learning for Computer Vision",
    by: "Stanford",
    type: "course",
    url: "https://cs231n.stanford.edu/",
    tracks: ["ml", "cs"],
    rating: 4,
    effort: "Notes + 3 assignments (~50 h)",
    verdict:
      "Famous for good reason, but the current recorded lectures are patchy — the *notes* and *assignments* are the real asset (build a CNN and backprop from scratch in numpy). Use Justin Johnson's Michigan course for video and CS231n for assignments.",
    when: "Phase 3-4 (W17-W33).",
  },
  {
    id: "eecs498",
    title: "EECS 498-007 / 598 Deep Learning for Computer Vision",
    by: "Justin Johnson, Michigan",
    type: "video",
    url: "https://web.eecs.umich.edu/~justincj/teaching/eecs498/",
    tracks: ["ml"],
    rating: 5,
    effort: "22 lectures (~30 h)",
    verdict:
      "Same DNA as CS231n (Johnson co-taught it) but fully recorded, better paced, and updated through transformers. This is the best single video course to actually learn deep learning for vision.",
    when: "Phase 3-4, watch alongside CS231n assignments.",
  },
  {
    id: "cs231a",
    title: "CS231A — Computer Vision: 3D Reconstruction to Recognition",
    by: "Stanford",
    type: "course",
    url: "https://web.stanford.edu/class/cs231a/",
    tracks: ["cs", "rob"],
    rating: 4,
    effort: "Course notes + PSets (~40 h)",
    verdict:
      "The geometric counterpart to CS231n: camera models, calibration, epipolar geometry, SfM, and a gentle on-ramp to Hartley & Zisserman. Notes are self-contained and free.",
    when: "Phase 4-5.",
  },
  {
    id: "tum-mvg",
    title: "Multiple View Geometry (IN2228)",
    by: "Daniel Cremers, TUM",
    type: "video",
    url: "https://cvg.cit.tum.de/teaching/online/mvg",
    tracks: ["cs", "rob"],
    rating: 5,
    effort: "14 lectures (~25 h) + exercises",
    verdict:
      "Rigorous, Lie-group-flavoured multiple view geometry from one of the best SLAM groups in the world. Cremers derives SE(3), the essential matrix, bundle adjustment and direct methods properly. Exactly the mathematical register MVA expects — and it makes Hartley & Zisserman readable.",
    when: "Phase 5-6 (W34-W68). Prerequisite for SLAM.",
  },
  {
    id: "hz",
    title: "Multiple View Geometry in Computer Vision (2nd ed.)",
    by: "Hartley & Zisserman",
    type: "book",
    url: "https://www.robots.ox.ac.uk/~vgg/hzbook/",
    tracks: ["cs"],
    rating: 4,
    effort: "Part 0-II (~50 h)",
    verdict:
      "The bible, and dense as concrete. Read it *after* Cremers, chapter by chapter, and only parts 0-II (projective geometry, camera models, two-view geometry) unless you go into research SfM. Sample chapters are free.",
    when: "Phase 6-7.",
  },
  {
    id: "colmap",
    title: "COLMAP",
    by: "Johannes Schönberger",
    type: "tool",
    url: "https://colmap.github.io/",
    tracks: ["cs", "rob"],
    rating: 4,
    effort: "1 weekend",
    verdict:
      "Run SfM/MVS on your own photos, then read the pipeline source. Best way to make bundle adjustment concrete before you implement a toy version yourself.",
    when: "Phase 5-6.",
  },
  {
    id: "orbslam3",
    title: "ORB-SLAM3",
    by: "UZ-SLAMLab",
    type: "repo",
    url: "https://github.com/UZ-SLAMLab/ORB_SLAM3",
    tracks: ["rob", "cs"],
    rating: 4,
    effort: "Read + run (~20 h)",
    verdict:
      "Production-grade visual-inertial SLAM in C++. Building it, running it on your own rosbags, then reading the tracking thread is a masterclass in real-time systems engineering.",
    when: "Phase 6-7, on the drone / racing car.",
  },

  // ─────────────────────────── ML / DL / RL ───────────────────────────
  {
    id: "karpathy",
    title: "Neural Networks: Zero to Hero",
    by: "Andrej Karpathy",
    type: "course",
    url: "https://karpathy.ai/zero-to-hero.html",
    tracks: ["ml"],
    rating: 5,
    effort: "8 videos, 2-4 h each, coded along (~45 h)",
    verdict:
      "The single highest-value thing on this list for you. Backprop from scratch → MLP → batchnorm → WaveNet → GPT → tokenizer, all typed live, all in ~1000 lines. Because you have zero ML experience but strong maths, this converts your maths into working code in ~6 weeks. Do not watch passively — type every line, then rebuild each notebook from an empty file.",
    when: "Phase 2 start (W8) → Phase 3. Gate: makemore + minGPT rebuilt from scratch.",
  },
  {
    id: "d2l",
    title: "Dive into Deep Learning",
    by: "Zhang, Lipton, Li, Smola (free)",
    type: "book",
    url: "https://d2l.ai/",
    tracks: ["ml"],
    rating: 4,
    effort: "Selected chapters (~40 h)",
    verdict:
      "Interactive book where every equation has runnable PyTorch next to it. Best reference when you need to implement a layer type you've only seen in a lecture. Weak as a linear read, excellent as a lookup.",
    when: "Throughout Phase 3-6.",
  },
  {
    id: "bishop-dl",
    title: "Deep Learning: Foundations and Concepts",
    by: "Chris Bishop & Hugh Bishop (2024)",
    type: "book",
    url: "https://www.bishopbook.com/",
    tracks: ["ml", "math"],
    rating: 5,
    effort: "~650 pp, read ch. 1-12 + 17-20 (~70 h)",
    verdict:
      "The modern replacement for PRML and Goodfellow: probabilistic framing, transformers, diffusion, all with clean maths and figures. For someone with your maths and no ML, this is the ideal main textbook. Free to read online.",
    when: "Phase 4-6, one chapter per fortnight.",
  },
  {
    id: "murphy",
    title: "Probabilistic Machine Learning I & II",
    by: "Kevin Murphy (free PDFs)",
    type: "book",
    url: "https://probml.github.io/pml-book/",
    tracks: ["ml", "math"],
    rating: 4,
    effort: "Reference, 2 × 1000 pp",
    verdict:
      "Encyclopedic and current. Book I for foundations you can look up, Book II (Advanced Topics) for inference, generative models, and RL when you need depth. Use as reference, not as a read.",
    when: "Phase 5+.",
  },
  {
    id: "cs229",
    title: "CS229 Machine Learning",
    by: "Andrew Ng / Stanford",
    type: "course",
    url: "https://cs229.stanford.edu/",
    tracks: ["ml"],
    rating: 3,
    effort: "Notes ~20 h",
    verdict:
      "The classical-ML core (GLMs, SVM+kernels, EM, bias-variance) done at the right mathematical level. You can skip the lectures and just work the course notes and problem sets — 3 weeks, not a semester.",
    when: "Phase 4, compressed.",
  },
  {
    id: "cs336",
    title: "CS336 — Language Modeling from Scratch",
    by: "Stanford (Hashimoto, Liang)",
    type: "course",
    url: "https://cs336.stanford.edu/",
    tracks: ["ml"],
    rating: 5,
    effort: "5 assignments, brutal (~120 h)",
    verdict:
      "You build a tokenizer, a transformer, the training loop, systems-level optimizations (flash attention, distributed), scaling laws, alignment. This is the deepest possible answer to 'I want to understand transformers and train/fine-tune from scratch'. Only attempt after Karpathy + solid PyTorch; then it is career-defining. Assignments and lecture videos are public.",
    when: "Phase 7 (W69-W85). Gate: Karpathy course complete + CUDA basics.",
  },
  {
    id: "cs224n",
    title: "CS224N — NLP with Deep Learning",
    by: "Stanford",
    type: "course",
    url: "https://web.stanford.edu/class/cs224n/",
    tracks: ["ml"],
    rating: 3,
    effort: "~35 h",
    verdict:
      "Good transformer/attention lectures and solid assignments, but partially superseded by CS336 for your goal. Cherry-pick the attention, tokenization, and RLHF lectures.",
    when: "Phase 6, selective.",
  },
  {
    id: "annotated-transformer",
    title: "The Annotated Transformer",
    by: "Harvard NLP",
    type: "repo",
    url: "https://nlp.seas.harvard.edu/annotated-transformer/",
    tracks: ["ml"],
    rating: 4,
    effort: "1 weekend",
    verdict:
      "Line-by-line PyTorch implementation of 'Attention is All You Need'. Perfect crosscheck after you've written your own transformer blind.",
    when: "Phase 5, right after your own implementation.",
  },
  {
    id: "attention",
    title: "Attention Is All You Need",
    by: "Vaswani et al., 2017",
    type: "paper",
    url: "https://arxiv.org/abs/1706.03762",
    tracks: ["ml"],
    rating: 5,
    effort: "3 h with pen",
    verdict:
      "Read it three times across the plan: once early (you'll understand 40%), once after implementing attention (90%), once when studying scaling (you'll see what they got lucky with).",
    when: "W20, W45, W75.",
  },
  {
    id: "resnet",
    title: "Deep Residual Learning (ResNet)",
    by: "He et al., 2015",
    type: "paper",
    url: "https://arxiv.org/abs/1512.03385",
    tracks: ["ml"],
    rating: 4,
    effort: "2 h",
    verdict:
      "The paper that made depth work, and your first 'reproduce a paper' target — a ResNet-18 on CIFAR-10 from scratch is the right week-long project.",
    when: "Phase 4.",
  },
  {
    id: "vit",
    title: "An Image is Worth 16x16 Words (ViT)",
    by: "Dosovitskiy et al., 2020",
    type: "paper",
    url: "https://arxiv.org/abs/2010.11929",
    tracks: ["ml"],
    rating: 4,
    effort: "2 h",
    verdict:
      "Where your vision and transformer tracks merge. Implement patch embedding + ViT-Tiny yourself; it's ~150 lines once you have attention.",
    when: "Phase 5-6.",
  },
  {
    id: "dinov2",
    title: "DINOv2 / self-supervised visual features",
    by: "Meta AI",
    type: "paper",
    url: "https://arxiv.org/abs/2304.07193",
    tracks: ["ml", "rob"],
    rating: 4,
    effort: "3 h + fine-tune",
    verdict:
      "Frozen DINOv2 features are the pragmatic backbone for robot perception with tiny datasets — exactly your situation on the arm and the hand. Learn to use, probe and fine-tune them.",
    when: "Phase 6-7, on robot projects.",
  },
  {
    id: "sutton",
    title: "Reinforcement Learning: An Introduction (2nd ed.)",
    by: "Sutton & Barto (free)",
    type: "book",
    url: "http://incompleteideas.net/book/the-book-2nd.html",
    tracks: ["ml"],
    rating: 5,
    effort: "Ch. 1-13 + exercises (~60 h)",
    verdict:
      "Still unmatched for foundations: bandits, MDPs, DP, MC, TD, n-step, function approximation, policy gradient. Do the programming exercises (gridworld, blackjack, mountain car) — they're short and they build correct intuition that deep RL courses assume.",
    when: "Phase 5-6 (W34-W68).",
  },
  {
    id: "silver",
    title: "RL Course (DeepMind × UCL)",
    by: "David Silver",
    type: "video",
    url: "https://www.davidsilver.uk/teaching/",
    tracks: ["ml"],
    rating: 4,
    effort: "10 lectures (~20 h)",
    verdict:
      "Clear, classic, maps 1:1 onto Sutton & Barto's first half. Use as the video pass over the book; the 2021 DeepMind×UCL series is a fine substitute.",
    when: "Phase 5, paired with Sutton.",
  },
  {
    id: "cs285",
    title: "CS285 — Deep Reinforcement Learning",
    by: "Sergey Levine, Berkeley",
    type: "course",
    url: "https://rail.eecs.berkeley.edu/deeprlcourse/",
    tracks: ["ml", "rob"],
    rating: 5,
    effort: "23 lectures + 5 homeworks (~80 h)",
    verdict:
      "The deep RL course, and Levine's group is the robot-learning group. Policy gradients → actor-critic → model-based → offline RL → imitation. Homeworks are real implementations. This is the direct bridge from your ML track to your quadruped and arm.",
    when: "Phase 7 (W69-W85). Gate: Sutton ch.1-13 + PyTorch fluency.",
  },
  {
    id: "spinningup",
    title: "Spinning Up in Deep RL",
    by: "OpenAI",
    type: "repo",
    url: "https://spinningup.openai.com/",
    tracks: ["ml"],
    rating: 4,
    effort: "~20 h",
    verdict:
      "Minimal, readable implementations of VPG/TRPO/PPO/DDPG/SAC plus a very good 'what to do and in what order' essay. Use its code as the reference implementation when yours won't learn.",
    when: "Phase 6-7.",
  },
  {
    id: "cleanrl",
    title: "CleanRL",
    by: "Costa Huang",
    type: "repo",
    url: "https://github.com/vwxyzjn/cleanrl",
    tracks: ["ml"],
    rating: 4,
    effort: "Read 3 files",
    verdict:
      "Single-file implementations with logged benchmarks. ppo_continuous_action.py is ~300 lines and is the fastest way to see every implementation detail that papers omit.",
    when: "Phase 7, during sim-to-real.",
  },
  {
    id: "diffusion-policy",
    title: "Diffusion Policy",
    by: "Chi et al., 2023",
    type: "paper",
    url: "https://diffusion-policy.cs.columbia.edu/",
    tracks: ["ml", "rob"],
    rating: 4,
    effort: "4 h + repo",
    verdict:
      "Current default for visuomotor manipulation from demonstrations — the realistic way to make your tendon hand and 6-DOF arm do something impressive without a reward function. Pairs with ACT.",
    when: "Phase 8, on the arm/hand.",
  },
  {
    id: "act",
    title: "ACT / ALOHA (Action Chunking Transformer)",
    by: "Zhao et al., 2023",
    type: "paper",
    url: "https://tonyzhaozh.github.io/aloha/",
    tracks: ["ml", "rob"],
    rating: 4,
    effort: "4 h + repo",
    verdict:
      "Imitation learning that works on cheap hardware with ~50 demos. The single most transferable recipe for your hand/arm projects, and the code is small enough to read fully.",
    when: "Phase 8.",
  },
  {
    id: "lilog",
    title: "Lil'Log",
    by: "Lilian Weng",
    type: "video",
    url: "https://lilianweng.github.io/",
    tracks: ["ml"],
    rating: 4,
    effort: "1 post = 1-2 h",
    verdict:
      "Best survey-style blog in ML: policy gradients, diffusion, attention variants, RLHF. Use a post as the map before diving into a paper cluster.",
    when: "Throughout.",
  },

  // ─────────────────────────── ROBOTICS ───────────────────────────
  {
    id: "modern-robotics",
    title: "Modern Robotics: Mechanics, Planning and Control",
    by: "Lynch & Park (book + Coursera + videos)",
    type: "book",
    url: "https://hades.mech.northwestern.edu/index.php/Modern_Robotics",
    tracks: ["rob", "math"],
    rating: 5,
    effort: "Book ch. 2-6, 8, 11 + 6-course specialization (~70 h)",
    verdict:
      "The reference for arm robotics, and it uses screw theory / Lie groups from page one — which is both the modern formulation and excellent maths training. Free PDF, free videos, free software library. Chapters 3-6 (rigid motions, forward/inverse kinematics, velocity kinematics) are exactly your 6-DOF arm and your tendon hand.",
    when: "Phase 2-4 (W8-W33). Prerequisite for the arm, the hand, the quadruped.",
  },
  {
    id: "articulated",
    title: "Articulated Robotics",
    by: "Josh Newans",
    type: "video",
    url: "https://articulatedrobotics.xyz/",
    tracks: ["rob"],
    rating: 5,
    effort: "~20 h",
    verdict:
      "The best practical ROS 2 teaching on the internet: URDF, gazebo, ros2_control, nav2, on a real mobile robot, without hand-waving. Do this early — ROS 2 is the lingua franca of your club and every robotics lab.",
    when: "Phase 1-2 (W3-W16).",
  },
  {
    id: "ros2",
    title: "ROS 2 documentation & tutorials",
    by: "Open Robotics",
    type: "tool",
    url: "https://docs.ros.org/en/jazzy/Tutorials.html",
    tracks: ["rob"],
    rating: 4,
    effort: "Beginner + intermediate tutorials (~20 h)",
    verdict:
      "Dry but authoritative. Do the CLI + client-library tutorials once, then learn the rest from Articulated Robotics and your own bugs. Know tf2, rosbag, and launch files cold.",
    when: "Phase 1-2, then reference.",
  },
  {
    id: "f1tenth",
    title: "F1TENTH Autonomous Racing course kit",
    by: "UPenn / TU Munich",
    type: "course",
    url: "https://f1tenth-coursekit.readthedocs.io/",
    tracks: ["rob", "cs"],
    rating: 5,
    effort: "10 modules + labs (~40 h)",
    verdict:
      "Purpose-built for your first-year project: 1/10-scale autonomous racing with ROS 2 — safety node, wall following, gap follow, scan matching, pure pursuit, MPC, particle filter localization. Steal their labs wholesale; the simulator lets you test before touching the car.",
    when: "Phase 1-3, in parallel with the club car.",
  },
  {
    id: "kalman-py",
    title: "Kalman and Bayesian Filters in Python",
    by: "Roger Labbe",
    type: "book",
    url: "https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python",
    tracks: ["rob", "math"],
    rating: 5,
    effort: "Ch. 1-11 as notebooks (~25 h)",
    verdict:
      "Jupyter-native, builds from g-h filters to KF/EKF/UKF with plots at each step. Fixes state estimation permanently — the skill that makes your drone and car work and that most students fake.",
    when: "Phase 3-4 (W17-W33). Prerequisite for SLAM and sensor fusion.",
  },
  {
    id: "probrob",
    title: "Probabilistic Robotics",
    by: "Thrun, Burgard, Fox",
    type: "book",
    url: "https://mitpress.mit.edu/9780262201629/probabilistic-robotics/",
    tracks: ["rob"],
    rating: 4,
    effort: "Ch. 2-9 (~40 h)",
    verdict:
      "The canonical treatment of Bayes filters, particle filters, EKF-SLAM, occupancy grids. Dense but the notation is worth internalising — everything in SLAM literature uses it.",
    when: "Phase 5-6, paired with Stachniss.",
  },
  {
    id: "stachniss",
    title: "SLAM / Mobile Sensing & Robotics lectures",
    by: "Cyrill Stachniss, Bonn",
    type: "video",
    url: "https://www.ipb.uni-bonn.de/online-training-robotics/index.html",
    tracks: ["rob"],
    rating: 5,
    effort: "~30 h",
    verdict:
      "Free, complete, and taught by someone who has shipped SLAM systems: ICP, graph-based SLAM, particle filters, photogrammetry. Better paced than the book and the exercises are in Python.",
    when: "Phase 5-6 (W34-W68).",
  },
  {
    id: "underactuated",
    title: "6.832 Underactuated Robotics",
    by: "Russ Tedrake, MIT",
    type: "course",
    url: "https://underactuated.mit.edu/",
    tracks: ["rob", "ml"],
    rating: 5,
    effort: "Notes + notebooks (~60 h)",
    verdict:
      "The intellectual heart of legged/flying robotics: dynamics, LQR, trajectory optimization, Lyapunov analysis, contact, and the honest version of 'RL vs control'. Requires your optimization track to be done first — and then it's the best thing you'll study all year. Interactive Drake notebooks.",
    when: "Phase 6-8 (W52+). Gate: Boyd ch.1-5 + Modern Robotics ch.8.",
  },
  {
    id: "manipulation",
    title: "6.4210 Robotic Manipulation",
    by: "Russ Tedrake, MIT",
    type: "course",
    url: "https://manipulation.mit.edu/",
    tracks: ["rob", "ml"],
    rating: 4,
    effort: "Notes + notebooks (~40 h)",
    verdict:
      "Perception → grasping → motion planning → learned policies for arms and hands, with runnable Drake examples. The right companion to your 6-DOF arm and tendon hand once kinematics is solid.",
    when: "Phase 7-8.",
  },
  {
    id: "lavalle",
    title: "Planning Algorithms",
    by: "Steven LaValle (free)",
    type: "book",
    url: "http://lavalle.pl/planning/",
    tracks: ["rob", "cs"],
    rating: 4,
    effort: "Ch. 2-7, 13-14 (~30 h)",
    verdict:
      "Configuration spaces, sampling-based planning (RRT/PRM), differential constraints. Free and definitive; read the chapters you need when the arm or the drone needs to plan.",
    when: "Phase 5-7, on demand.",
  },
  {
    id: "brunton",
    title: "Control Bootcamp",
    by: "Steve Brunton, U. Washington",
    type: "video",
    url: "https://www.youtube.com/playlist?list=PLMrJAkhIeNNR20Mz-VpzgfQs5zrYi085m",
    tracks: ["rob", "math"],
    rating: 5,
    effort: "~35 videos (~12 h)",
    verdict:
      "State-space control, controllability, LQR, Kalman, robust control, in short, extremely clear videos with MATLAB/Python demos. The fastest possible route from prépa linear algebra to controlling a real machine. Watch it before you tune another PID by hand.",
    when: "Phase 2-3 (W8-W25).",
  },
  {
    id: "uavbook",
    title: "Small Unmanned Aircraft: Theory and Practice",
    by: "Beard & McLain",
    type: "book",
    url: "https://github.com/randybeard/mavsim_public",
    tracks: ["rob"],
    rating: 4,
    effort: "Ch. 1-10 + simulator project (~40 h)",
    verdict:
      "The standard fixed-wing UAV text with a full Python simulation project (mavsim): aerodynamics, state estimation, autopilot cascade, path following. Precisely the theory your morphing-wing glider needs, and the simulator lets you test control laws before you crash carbon fibre.",
    when: "Phase 5-7, before/while building the glider.",
  },
  {
    id: "px4",
    title: "PX4 Autopilot / ArduPilot",
    by: "PX4 Dev Team",
    type: "tool",
    url: "https://docs.px4.io/",
    tracks: ["rob"],
    rating: 4,
    effort: "Setup + custom module (~25 h)",
    verdict:
      "Don't write your own flight stack — extend one. PX4's uORB architecture and offboard mode let you put your own guidance/AI module on top of a proven attitude controller. Read the control architecture pages, then write one custom module.",
    when: "Phase 6-8, on the glider/drone.",
  },
  {
    id: "mujoco",
    title: "MuJoCo + MJX",
    by: "Google DeepMind",
    type: "tool",
    url: "https://mujoco.readthedocs.io/",
    tracks: ["rob", "ml"],
    rating: 5,
    effort: "~20 h to fluency",
    verdict:
      "Fast, free, differentiable-ish physics — the standard for robot learning. Model your own arm/quadruped in MJCF, then train policies in MJX on GPU. Sim skills are what let you keep working when hardware is broken (it will be).",
    when: "Phase 5 onward.",
  },
  {
    id: "isaaclab",
    title: "NVIDIA Isaac Lab / Isaac Sim",
    by: "NVIDIA",
    type: "tool",
    url: "https://isaac-sim.github.io/IsaacLab/",
    tracks: ["rob", "ml"],
    rating: 3,
    effort: "~25 h, needs an RTX GPU",
    verdict:
      "Massively parallel sim with strong sim-to-real recipes for legged robots — but heavyweight and version-fragile. Use it only for the quadruped locomotion policy, after MuJoCo. Runs on the club/university GPUs, not the Jetson.",
    when: "Phase 7-8, quadruped only.",
  },
  {
    id: "cs123",
    title: "CS 123 — Building AI-Enabled Robots (Stanford Pupper)",
    by: "Stanford",
    type: "course",
    url: "https://cs123-stanford.readthedocs.io/",
    tracks: ["rob", "ml"],
    rating: 4,
    effort: "10 labs (~30 h)",
    verdict:
      "Complete open course for a low-cost quadruped: motor control, kinematics, system ID, sim-to-real RL, vision. If you build the dog, build it on this scaffold instead of inventing one — then replace their policy with yours.",
    when: "Phase 7-8, quadruped project.",
  },
  {
    id: "leaphand",
    title: "LEAP Hand (v1 / v2)",
    by: "CMU (Shaw, Pathak et al.)",
    type: "repo",
    url: "https://leaphand.com/",
    tracks: ["rob", "ml"],
    rating: 5,
    effort: "Assembly ~4-8 h, then research",
    verdict:
      "Open-source, ~$200-2000 anthropomorphic hand with published CAD, firmware and learning stack. Even if you build your own tendon hand, read their tendon routing, motor sizing and calibration decisions first — it will save you two failed prototypes.",
    when: "Phase 6-8, tendon hand project.",
  },
  {
    id: "fusion",
    title: "Fusion 360 for makers (design → 3D print → assembly)",
    by: "Autodesk (free student licence)",
    type: "tool",
    url: "https://www.autodesk.com/products/fusion-360/students-teachers-educators",
    tracks: ["rob"],
    rating: 4,
    effort: "~20 h to competence",
    verdict:
      "CAD is the bottleneck skill for everything you want to build. Parametric modelling, joints, simple FEA and CAM. Get to 'I can design a printable bracket with proper tolerances' fast; refine over projects.",
    when: "Phase 1-2, then continuously.",
  },

  // ─────────────────────────── INTERVIEW / CAREER ───────────────────────────
  {
    id: "ml-interviews",
    title: "Introduction to Machine Learning Interviews",
    by: "Chip Huyen (free)",
    type: "book",
    url: "https://huyenchip.com/ml-interviews-book/",
    tracks: ["ml", "cs"],
    rating: 4,
    effort: "~10 h",
    verdict:
      "Covers what ML interviews actually ask (maths, modelling, deployment) plus 200+ questions with the right level of ambiguity. Good self-assessment tool at the end of each year.",
    when: "Phase 6 and Phase 8.",
  },
  {
    id: "epi",
    title: "Elements of Programming Interviews (C++ edition)",
    by: "Aziz, Lee, Prakash",
    type: "book",
    url: "https://elementsofprogramminginterviews.com/",
    tracks: ["cs"],
    rating: 3,
    effort: "~40 h, selective",
    verdict:
      "Harder and better written than Cracking the Coding Interview, with idiomatic C++. Use the 'problem of the day' structure in the final six months before internship interviews.",
    when: "Phase 8.",
  },
  {
    id: "mva-cours",
    title: "MVA course catalogue",
    by: "Master MVA, ENS Paris-Saclay",
    type: "course",
    url: "https://www.master-mva.com/cours/",
    tracks: ["math", "ml", "cs"],
    rating: 5,
    effort: "1 h/term to re-read",
    verdict:
      "Your actual target document. Every module lists its prerequisites and its evaluation format. Re-read it each semester and check the gap between the prerequisites listed there and what you can currently do — that gap is your syllabus.",
    when: "End of every phase.",
  },
];

export const resourceById = Object.fromEntries(resources.map((r) => [r.id, r]));
