import type { RoboticsProject } from "./types";

/**
 * Seven builds across two years, sequenced so each one lands right after the
 * maths and code that make it non-trivial. Prices are realistic 2026 European
 * retail in euros; club-owned hardware is listed at 0 with a note so the
 * total reflects what actually leaves your pocket.
 */
export const roboticsProjects: RoboticsProject[] = [
  {
    id: "rob-car",
    name: "Autonomous racing car",
    window: "W1 — W42 · Sep 2026 — Jun 2027",
    weeks: [1, 42],
    status: "club",
    pitch:
      "Already in progress, so it is your teaching platform rather than your showcase: the place where perception, estimation and control get debugged on real hardware while you still know almost nothing. The one thing to protect is scope — full-vision autonomy on a known track, timed laps, logged data. Not a research contribution, and it does not need to be.",
    skills: [
      "ROS 2 as a real system: nodes, TF, launch, rosbag, deterministic replay",
      "Camera calibration and reprojection error you actually read",
      "Particle-filter localisation on a known map",
      "Pure pursuit vs Stanley vs MPC, compared on logged laps",
      "Failure discipline: every crash produces a log and a diagnosis",
    ],
    concepts: [
      "Rigid-body transforms and TF trees",
      "Bayes filters and particle filters",
      "Pinhole camera model, intrinsics, distortion",
      "Pure pursuit geometry and lookahead tuning",
      "Model-predictive control with a kinematic bicycle model",
    ],
    milestones: [
      { id: "car-m1", text: "F1TENTH simulator running, wall-following in sim (W2-W5)" },
      { id: "car-m2", text: "Your own ROS 2 package: teleop, safety node, rosbag pipeline (W8-W12)" },
      { id: "car-m3", text: "Calibrated camera + lidar, TF tree correct, extrinsics measured (W17-W20)" },
      { id: "car-m4", text: "Particle-filter localisation on the club track (W22-W25)" },
      { id: "car-m5", text: "First full autonomous lap, logged (W34)" },
      { id: "car-m6", text: "Controller comparison written up with lap times and tracking error (W35)" },
      { id: "car-m7", text: "MPC running onboard, beating pure pursuit on lap time (W55)" },
    ],
    bom: [
      { item: "1/10 scale chassis (Traxxas Slash 4x4 class)", qty: "1", cost: 0, note: "Club-owned, already purchased" },
      { item: "VESC 6 MkVI motor controller", qty: "1", cost: 0, note: "Club-owned" },
      { item: "2D lidar (RPLidar S2 class, 30 m)", qty: "1", cost: 0, note: "Club-owned" },
      { item: "Jetson Orin Nano 8 GB dev kit", qty: "1", cost: 300, note: "Your contribution — the vision stack needs the GPU" },
      { item: "Intel RealSense D435i", qty: "1", cost: 320, note: "Stereo + IMU; this is what makes it a vision car" },
      { item: "Global-shutter mono camera (OV9281 class)", qty: "1", cost: 60, note: "Rolling shutter ruins fast VO — do not skip" },
      { item: "4S LiPo 6000 mAh + charger", qty: "2 + 1", cost: 130, note: "Two packs means twice the testing per session" },
      { item: "Wheel encoders + BNO085 IMU", qty: "1 set", cost: 70, note: "Odometry for the filter" },
      { item: "Crash spares: A-arms, tyres, bearings", qty: "1 set", cost: 90, note: "You will crash it. Budget for it up front" },
      { item: "Wiring, connectors, fuses, mounts", qty: "—", cost: 40, note: "Always underestimated" },
    ],
    budget: 1010,
    res: ["f1tenth", "ros2", "probrob", "kalman-py", "underactuated"],
  },
  {
    id: "rob-arm",
    name: "6-DOF robotic arm",
    window: "W36 — W51 · Jun — Sep 2027",
    weeks: [36, 51],
    status: "solo",
    pitch:
      "The build that forces you to understand dynamics rather than kinematics. Torque-controlled joints mean the mass matrix, Coriolis terms and gravity compensation stop being symbols in Modern Robotics ch.8 and become the reason your arm holds a pose with the motors nearly free. It is also the mount point for the hand and the platform for every imitation-learning experiment after Phase 5.",
    skills: [
      "Actuator sizing derived from the dynamics, not guessed",
      "Cycloidal / belt reduction design with real backlash measurement",
      "Field-oriented torque control via ODrive, with encoder calibration",
      "ros2_control hardware interface written by you",
      "IK: analytic where possible, damped least squares where not",
      "Hand-eye calibration and repeatability measured with an indicator",
    ],
    concepts: [
      "Product of exponentials and the space/body Jacobian",
      "Lagrangian dynamics: mass matrix, Coriolis, gravity vector",
      "Recursive Newton-Euler for inverse dynamics",
      "Computed-torque and impedance control, and their stability",
      "Damped least squares near kinematic singularities",
      "Trajectory time-scaling and via-point blending",
    ],
    milestones: [
      { id: "arm-m1", text: "Workspace, reach and payload spec with actuator sizing spreadsheet (W36)" },
      { id: "arm-m2", text: "Full CAD, reduction choice justified, first joint printed and fitted (W37)" },
      { id: "arm-m3", text: "Joints 1-3 assembled, closed-loop position control on one axis (W38)" },
      { id: "arm-m4", text: "All 6 joints assembled, encoders calibrated, TF tree published (W39)" },
      { id: "arm-m5", text: "Gravity compensation: holds any pose with near-zero commanded stiffness (W39)" },
      { id: "arm-m6", text: "IK + Cartesian jogging + MoveIt 2 planning (W40-W41)" },
      { id: "arm-m7", text: "Vision-guided pick-and-place, 20 consecutive attempts on video (W42)" },
      { id: "arm-m8", text: "Repeatability measured with a dial indicator, number published (W43)" },
    ],
    bom: [
      { item: "ODrive S1 motor controllers", qty: "3", cost: 480, note: "Joints 1-3, the torque-critical ones" },
      { item: "BLDC gimbal/hobby motors (D5065 class)", qty: "3", cost: 270, note: "Sized from the payload dynamics, not from a video" },
      { item: "Printed cycloidal reducers + bearing sets", qty: "3", cost: 135, note: "Cheap, low backlash if printed well; measure it" },
      { item: "AS5047P magnetic encoders", qty: "6", cost: 72, note: "One per joint, absolute-ish and cheap" },
      { item: "Dynamixel XM430 wrist servos", qty: "3", cost: 270, note: "Wrist needs precision more than torque" },
      { item: "Aluminium extrusion + machined plates", qty: "—", cost: 180, note: "Stiffness is the difference between a demo and a tool" },
      { item: "48 V 500 W PSU", qty: "1", cost: 90, note: "Headroom for torque transients" },
      { item: "GT2 pulleys, belts, bearings, fasteners", qty: "—", cost: 120, note: "" },
      { item: "PETG + CF-nylon filament", qty: "5 kg", cost: 120, note: "CF-nylon for the load-bearing links only" },
      { item: "E-stop, safety relay, enclosure", qty: "1", cost: 80, note: "A torque-controlled arm can hurt you. Non-negotiable" },
      { item: "Drag chain, cabling, connectors", qty: "—", cost: 70, note: "" },
    ],
    budget: 1987,
    res: ["modern-robotics", "articulated", "ros2", "fusion", "manipulation"],
  },
  {
    id: "rob-hand",
    name: "Tendon-driven robotic hand (10 servos)",
    window: "W44 — W77 · Jul 2027 — Mar 2028",
    weeks: [44, 77],
    status: "solo",
    pitch:
      "Your best research asset. Dexterous manipulation is where robot learning is genuinely unsolved, and a working tendon hand plus a teleoperation rig means you can generate the datasets that most students have to beg for. Treat the LEAP Hand as the reference design and be explicit about what you copy — reimplementing a validated design well is a stronger signal than a novel design that does not close a gripper.",
    skills: [
      "Tendon routing, pulley radii and tension budgeting",
      "Underactuated mechanism design with return springs",
      "Serial-bus servo control at 10+ DOF with a real control loop",
      "Grasp primitives and finger IK",
      "Current-sense force feedback, and its limits",
      "Blind evaluation protocols for manipulation success rates",
    ],
    concepts: [
      "Tendon transmission kinematics and coupling matrices",
      "Grasp taxonomy: power, pinch, tripod, lateral",
      "Form and force closure",
      "Contact models and friction cones",
      "Action chunking and why it fixes jittery policies",
      "Behaviour cloning, and the distribution shift that breaks it",
    ],
    milestones: [
      { id: "hand-m1", text: "Kinematic design: 10 servos allocated, routing and pulley radii computed (W44)" },
      { id: "hand-m2", text: "Two fingers printed, assembled, tendon travel validated (W45)" },
      { id: "hand-m3", text: "All fingers built, servo bus + power budget + current sensing working (W45-W46)" },
      { id: "hand-m4", text: "Grasp primitives working; hand mounted on the arm, one 16-DOF stack (W46)" },
      { id: "hand-m5", text: "Teleoperation rig recording synchronised video + joint states (W48)" },
      { id: "hand-m6", text: "50 demonstrations of one task, dataset loader written (W48)" },
      { id: "hand-m7", text: "ACT and diffusion policies trained and compared on your data (W49)" },
      { id: "hand-m8", text: "300+ demonstrations across 3 tasks (W76)" },
      { id: "hand-m9", text: "Blind 50-trial evaluation per task, run by someone else, table published (W77)" },
    ],
    bom: [
      { item: "STS3215 serial-bus servos", qty: "10", cost: 250, note: "Position feedback + current sense at hobby prices" },
      { item: "Servo bus driver + 12 V 10 A PSU", qty: "1", cost: 60, note: "" },
      { item: "Dyneema tendon line + PTFE tubing", qty: "—", cost: 30, note: "Pre-stretch it or your calibration drifts daily" },
      { item: "Miniature bearings, springs, pulleys", qty: "—", cost: 70, note: "" },
      { item: "Tough resin + filament", qty: "—", cost: 90, note: "Resin for phalanges, filament for the palm" },
      { item: "FSR / current-sense boards", qty: "5", cost: 60, note: "Crude force feedback; do not oversell it" },
      { item: "Machined wrist flange to the arm", qty: "1", cost: 50, note: "" },
      { item: "Spare servos", qty: "3", cost: 75, note: "You will stall and kill at least two" },
      { item: "Silicone fingertip moulding kit", qty: "1", cost: 45, note: "Friction at the fingertip changes everything" },
    ],
    budget: 730,
    res: ["leaphand", "manipulation", "act", "diffusion-policy", "articulated"],
  },
  {
    id: "rob-glider",
    name: "Morphing-wing gliding drone",
    window: "W26 — W42 · Mar — Jun 2027",
    weeks: [26, 42],
    status: "solo",
    pitch:
      "The most original of your builds and the one most likely to fail interestingly. A variable-geometry wing turns control allocation into a real problem: more actuators than degrees of freedom you care about, coupled aerodynamics, and a plant that changes shape mid-flight. Keep it unpowered and RC-controlled first; embedded AI path planning comes later on the quadcopter, where crashes are cheaper.",
    skills: [
      "Foam-core and carbon composite airframe construction",
      "Aerodynamic estimation good enough to size a wing (XFLR5 level)",
      "Control allocation for redundant actuators",
      "PX4 airframe configuration and log analysis",
      "Instrumented flight testing: IMU, airspeed, GPS, and reading the logs",
    ],
    concepts: [
      "Lift, drag polars, glide ratio, and the sink-rate tradeoff",
      "Longitudinal and lateral stability, static margin",
      "Control allocation as a constrained least-squares problem",
      "Actuator saturation and anti-windup",
      "System identification from flight logs",
    ],
    milestones: [
      { id: "gld-m1", text: "Aero sizing: wing area, aspect ratio, static margin, target glide ratio (W26-W29)" },
      { id: "gld-m2", text: "Wing CAD with morphing ribs; mechanism bench-tested off the airframe (W32)" },
      { id: "gld-m3", text: "Airframe built, CG set, hand-launch glide test (W32)" },
      { id: "gld-m4", text: "Flight controller installed, IMU + airspeed logging (W33)" },
      { id: "gld-m5", text: "Control allocation implemented, morphing commanded in flight (W73)" },
      { id: "gld-m6", text: "Hardware-in-the-loop sim matching real logs within 15% (W74)" },
      { id: "gld-m7", text: "Instrumented glide tests vs the aero model, written up (W75)" },
    ],
    bom: [
      { item: "Carbon spars, tubes, XPS/EPP foam cores", qty: "—", cost: 120, note: "" },
      { item: "Metal-gear micro servos", qty: "8", cost: 120, note: "Morphing ribs need more actuators than a normal wing" },
      { item: "Pixhawk 6C mini flight controller", qty: "1", cost: 200, note: "PX4 support is why; do not use a toy FC" },
      { item: "Pitot tube + differential pressure sensor", qty: "1", cost: 45, note: "Airspeed is the measurement that makes the data useful" },
      { item: "GPS module (M10 class)", qty: "1", cost: 35, note: "" },
      { item: "SiK telemetry radio pair (868 MHz)", qty: "1", cost: 60, note: "Live logs beat post-flight guessing" },
      { item: "ELRS transmitter + receivers", qty: "1", cost: 0, note: "Club radio — borrow rather than buy" },
      { item: "3S 2200 mAh LiPo + charger", qty: "3 + 1", cost: 70, note: "" },
      { item: "Epoxy, glass cloth, vacuum bagging consumables", qty: "—", cost: 80, note: "" },
    ],
    budget: 730,
    res: ["uavbook", "px4", "brunton", "lavalle"],
  },
  {
    id: "rob-quad",
    name: "Quadruped robot",
    window: "W56 — W82 · Oct 2027 — Apr 2028",
    weeks: [56, 82],
    status: "club+solo",
    pitch:
      "The centrepiece of year two and the most expensive build, so the design review in W57 exists to stop you buying twelve actuators for a robot that cannot stand. Its value is that it makes the two halves of your plan collide: convex MPC from Underactuated Robotics on one side, PPO policies trained in Isaac on the other, on the same hardware, with the comparison written up. That comparison is a portfolio piece by itself.",
    skills: [
      "Quasi-direct-drive actuation and mass budgeting",
      "Real-time control split between a Linux SBC and a microcontroller",
      "Convex MPC with ground-reaction-force allocation",
      "Contact-aware state estimation (IMU + leg odometry EKF)",
      "Massively parallel RL training and honest sim-to-real measurement",
    ],
    concepts: [
      "SLIP model, ZMP, capture point, Raibert heuristic",
      "Hybrid dynamics and contact complementarity",
      "LQR and iLQR, then MPC as receding-horizon optimisation",
      "Floating-base kinematics and contact Jacobians",
      "Domain randomisation and actuator networks",
      "PPO with massive parallelism, and where it beats a model",
    ],
    milestones: [
      { id: "qd-m1", text: "Design review doc: kinematics, torque analysis, mass budget, BOM (W57)" },
      { id: "qd-m2", text: "Full CAD, actuators ordered against the BOM (W58)" },
      { id: "qd-m3", text: "Four legs machined and assembled, one leg torque-tested on the bench (W59)" },
      { id: "qd-m4", text: "Body assembled, power distribution + E-stop, first standing test (W60-W61)" },
      { id: "qd-m5", text: "Leg IK + joint-level control with torque limits (W62)" },
      { id: "qd-m6", text: "Standing balance via QP ground-reaction-force allocation (W62)" },
      { id: "qd-m7", text: "Convex MPC trot in MuJoCo, then on hardware (W63-W64)" },
      { id: "qd-m8", text: "EKF state estimation validated against ground truth (W66)" },
      { id: "qd-m9", text: "Autonomous walk to a visual goal using your own SLAM (W66)" },
      { id: "qd-m10", text: "Isaac-trained policy deployed; sim-to-real gap quantified (W80)" },
      { id: "qd-m11", text: "Rough terrain + push recovery, 20 trials documented (W81)" },
    ],
    bom: [
      { item: "QDD actuators (MyActuator RMD-X6 class)", qty: "12", cost: 1920, note: "The whole project's cost. Do not order before the W57 design review" },
      { item: "Carbon plate + machined brackets", qty: "—", cost: 180, note: "" },
      { item: "Raspberry Pi 5 + Teensy 4.1", qty: "1 each", cost: 130, note: "Pi for planning, Teensy for the 1 kHz loop" },
      { item: "IMU: BNO085 + ICM-42688", qty: "1 each", cost: 60, note: "Two IMUs so you can tell drift from a bug" },
      { item: "6S 6000 mAh LiPo + BMS + charger", qty: "2 + 1", cost: 160, note: "" },
      { item: "CAN bus wiring, connectors, strain relief", qty: "—", cost: 60, note: "CAN wiring failures will cost you a week if done badly" },
      { item: "Foot contact sensors", qty: "4", cost: 40, note: "Contact detection makes the EKF work" },
      { item: "Printing, spares, replacement gearboxes", qty: "—", cost: 100, note: "" },
    ],
    budget: 2650,
    res: ["cs123", "underactuated", "mujoco", "isaaclab", "modern-robotics", "kalman-py"],
  },
  {
    id: "rob-drone",
    name: "Autonomous quadcopter with onboard AI",
    window: "W69 — W83 · Jan — Apr 2028",
    weeks: [69, 83],
    status: "solo",
    pitch:
      "Where the embedded-AI path planning you wanted for the glider actually gets built, because a quadcopter can hover, fail safely into a net, and be repaired in twenty minutes. Onboard means onboard: planning and obstacle avoidance running on the companion computer at 20 Hz, not streamed to a laptop. That constraint is the whole educational value.",
    skills: [
      "PX4 offboard control via MAVROS, and its failure modes",
      "EKF2 tuning from real logs",
      "Onboard planning: RRT* / A* on a voxel grid under a compute budget",
      "Stereo depth to occupancy mapping in real time",
      "Flight-test discipline: tether, net, checklists, incremental risk",
    ],
    concepts: [
      "Quadrotor dynamics and differential flatness",
      "Cascaded attitude/position control",
      "Configuration space, sampling-based planning, and asymptotic optimality",
      "Occupancy grids and probabilistic mapping",
      "Latency budgets: perception-to-actuation delay as a control problem",
    ],
    milestones: [
      { id: "dr-m1", text: "PX4 SITL + MAVROS offboard mission in simulation (W69)" },
      { id: "dr-m2", text: "Airframe built, first manual hover, logs clean (W69-W70)" },
      { id: "dr-m3", text: "EKF2 tuned; state estimate trusted in position mode (W70)" },
      { id: "dr-m4", text: "RRT* planner running onboard within the compute budget (W71)" },
      { id: "dr-m5", text: "Stereo-depth obstacle avoidance at 20 Hz onboard (W72)" },
      { id: "dr-m6", text: "Autonomous mission: takeoff, vision-based waypoints, landing (W83)" },
    ],
    bom: [
      { item: '5" quad frame + motors + ESC kit', qty: "1", cost: 220, note: "Build it yourself; a bound kit teaches nothing" },
      { item: "Pixhawk 6X / Cube Orange", qty: "1", cost: 260, note: "" },
      { item: "Jetson Orin Nano Super 8 GB (companion)", qty: "1", cost: 280, note: "Dedicated, not shared with the car" },
      { item: "OAK-D Lite depth camera", qty: "1", cost: 250, note: "On-camera depth saves your compute budget" },
      { item: "GPS + telemetry radios", qty: "1 set", cost: 90, note: "" },
      { item: "Props, spares, 4S batteries", qty: "—", cost: 130, note: "" },
      { item: "Prop guards, tether rig, indoor test net", qty: "1", cost: 120, note: "Cheaper than one destroyed Jetson or one injury" },
    ],
    budget: 1350,
    res: ["px4", "uavbook", "lavalle", "probrob"],
  },
  {
    id: "rob-lab",
    name: "Research platform & shared lab",
    window: "W48 — W94 · Aug 2027 — Jul 2028",
    weeks: [48, 94],
    status: "solo",
    pitch:
      "Not a robot — the infrastructure that makes the other six produce results. A teleoperation leader arm, a local GPU so you can iterate without queueing for cluster time, calibrated cameras for data collection, and enough bench instrumentation to diagnose electrical problems instead of guessing. This line item is what turns builds into a research profile, and it is the one students always cut first.",
    skills: [
      "Dataset engineering: synchronised multi-camera capture, dataset cards",
      "Reproducible experiment infrastructure: configs, seeds, tracking",
      "Local training loop fast enough to iterate daily",
      "Electrical debugging with a scope instead of intuition",
    ],
    concepts: [
      "Time synchronisation across sensors, and what desync does to a policy",
      "Train/eval splits for robot data, and why random splits lie",
      "Bootstrap confidence intervals on success rates",
      "Blind evaluation and operator bias",
    ],
    milestones: [
      { id: "lab-m1", text: "Teleop leader arm built and mapped to the follower (W48)" },
      { id: "lab-m2", text: "GPU workstation running training jobs locally (W49)" },
      { id: "lab-m3", text: "Multi-camera synchronised capture rig, dataset card written (W76)" },
      { id: "lab-m4", text: "Experiment infra: configs, seeds, tracking, clean-clone reproduction (W86)" },
      { id: "lab-m5", text: "Evaluation harness with bootstrap CIs, used for the paper (W88)" },
    ],
    bom: [
      { item: "Teleoperation leader arm (SO-100 class)", qty: "1", cost: 250, note: "The cheapest thing here and the highest leverage" },
      { item: "Used RTX 3090 24 GB + PSU upgrade", qty: "1", cost: 700, note: "24 GB matters more than speed for policy and LM work" },
      { item: "USB global-shutter cameras", qty: "3", cost: 150, note: "Wrist, overhead, side — the standard manipulation rig" },
      { item: "Bench PSU, entry oscilloscope, soldering station", qty: "—", cost: 200, note: "You cannot debug a CAN bus by staring at it" },
    ],
    budget: 1300,
    res: ["act", "diffusion-policy", "isaaclab", "missing-semester"],
  },
];

export const ROBOTICS_BUDGET_CAP = 10_000;

export const roboticsTotal = roboticsProjects.reduce(
  (s, p) => s + p.budget,
  0,
);

export const BUDGET_NOTE =
  "Total planned spend is under the €10 000 cap with roughly €240 held back, which is deliberate: something will cost more than this list says, and a budget with no slack forces you to cancel a project rather than absorb a surprise. Two structural choices worth defending — the quadruped's twelve actuators are 27% of the entire budget and are the one purchase gated behind a written design review, and the €1 300 'lab' line buys no robot at all, which is exactly why it is the line most students cut and then spend a year queueing for cluster time and hand-labelling desynchronised video.";
